language: sh

addons:
    apt:
        update: true
    packages:
        - dmidecode
        - virt-what

script:
    - DISTROFORMAT="export" ./distro
    
after_script:
    - env
    - cat /proc/1/cgroup
    - cat /proc/1/sched
    - cat /proc/self/cgroup
    - cat /usr/bin/systemd-detect-virt
    - cat /sys/devices/virtual/dmi/id/product_name
    - cat /proc/cpuinfo
    - sudo dmidecode -s system-product-name
    - sudo virt-what

jobs:
    include:
        - dist: trusty
          arch: amd64
        - dist: xenial
          arch: amd64
        - dist: xenial
          arch: arm64
        - dist: xenial
          arch: ppc64le