language: sh

before_install:
    - sudo apt-get -y install dmidecode
    - sudo apt-get -y install virt-what

addons:
    apt:
        update: true

script:
    - DISTROFORMAT="export" ./distro
    
after_script:
    - env
    - cat /proc/1/cgroup
    - cat /proc/device-tree/hypervisor/compatible
    - cat /sys/devices/virtual/dmi/id/product_name
    - cat /proc/cpuinfo
    - /usr/bin/systemd-detect-virt
    - sudo dmidecode -s system-product-name
    - sudo virt-what

jobs:
    include:
        - dist: trusty
          arch: amd64
        - dist: xenial
          arch: amd64
        - dist: xenial
          arch: arm64
        - dist: xenial
          arch: ppc64le